// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/technologies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technologies"
                ],
                "summary": "List all technologies",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "Nodejs",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_TechnologyDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technologies"
                ],
                "summary": "Create a technology",
                "parameters": [
                    {
                        "minLength": 3,
                        "type": "string",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minLength": 3,
                        "type": "string",
                        "name": "slug",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            }
        },
        "/technologies/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technologies"
                ],
                "summary": "Find a technology",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Technology ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technologies"
                ],
                "summary": "Update a technology",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Technology ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "slug",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technologies"
                ],
                "summary": "Delete a technology",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Technology ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "Ana",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_UserDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/icomphub-api_dtos.Response-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "codes.Code": {
            "type": "string",
            "enum": [
                "unknow_error",
                "invalid_params",
                "get_all_users",
                "count_all_users",
                "find_user",
                "update_user",
                "create_user",
                "delete_user",
                "error_getting_users",
                "error_counting_users",
                "get_all_technologies",
                "count_all_technologies",
                "find_technology",
                "update_technology",
                "create_technology",
                "delete_technology",
                "error_getting_technologies",
                "error_counting_technologies",
                "error_finding_technology",
                "error_updating_technology",
                "error_creating_technology",
                "error_deleting_technology"
            ],
            "x-enum-varnames": [
                "UnknowError",
                "InvalidParams",
                "GetAllUsers",
                "CountAllUsers",
                "FindUser",
                "UpdateUser",
                "CreateUser",
                "DeleteUser",
                "ErrorGettingAllUsers",
                "ErrorCoutingAllUsers",
                "GetAllTechnologies",
                "CountAllTechnologies",
                "FindTechnology",
                "UpdateTechnology",
                "CreateTechnology",
                "DeleteTechnology",
                "ErrorGettingAllTechnologies",
                "ErrorCoutingAllTechnologies",
                "ErrorFindingTechnology",
                "ErrorUpdatingTechnology",
                "ErrorCreatingTechnology",
                "ErrorDeletingTechnology"
            ]
        },
        "dtos.TechnologyDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "dtos.UserDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "personal_email": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/enums.SystemRoleEnum"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "enums.SystemRoleEnum": {
            "type": "string",
            "enum": [
                "admin",
                "user",
                "professor"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleUser",
                "RoleProfessor"
            ]
        },
        "icomphub-api_dtos.PaginationDTO-dtos_TechnologyDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.TechnologyDTO"
                    }
                },
                "page_number": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "total_items": {
                    "type": "integer",
                    "example": 20
                },
                "total_pages": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "icomphub-api_dtos.PaginationDTO-dtos_UserDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.UserDTO"
                    }
                },
                "page_number": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 10
                },
                "total_items": {
                    "type": "integer",
                    "example": 20
                },
                "total_pages": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "icomphub-api_dtos.Response-any": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/codes.Code"
                        }
                    ],
                    "example": "USER_CREATED"
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "icomphub-api_dtos.Response-dtos_TechnologyDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/codes.Code"
                        }
                    ],
                    "example": "USER_CREATED"
                },
                "data": {
                    "$ref": "#/definitions/dtos.TechnologyDTO"
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_TechnologyDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/codes.Code"
                        }
                    ],
                    "example": "USER_CREATED"
                },
                "data": {
                    "$ref": "#/definitions/icomphub-api_dtos.PaginationDTO-dtos_TechnologyDTO"
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_UserDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/codes.Code"
                        }
                    ],
                    "example": "USER_CREATED"
                },
                "data": {
                    "$ref": "#/definitions/icomphub-api_dtos.PaginationDTO-dtos_UserDTO"
                },
                "message": {
                    "type": "string",
                    "example": "User created successfully"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
