definitions:
  codes.Code:
    enum:
    - unknow_error
    - invalid_params
    - get_all_users
    - count_all_users
    - find_user
    - update_user
    - create_user
    - delete_user
    - error_getting_users
    - error_counting_users
    - error_finding_user
    - error_updating_user
    - error_creating_user
    - error_deleting_user
    - get_all_technologies
    - count_all_technologies
    - find_technology
    - update_technology
    - create_technology
    - delete_technology
    - error_getting_technologies
    - error_counting_technologies
    - error_finding_technology
    - error_updating_technology
    - error_creating_technology
    - error_deleting_technology
    type: string
    x-enum-varnames:
    - UnknowError
    - InvalidParams
    - GetAllUsers
    - CountAllUsers
    - FindUser
    - UpdateUser
    - CreateUser
    - DeleteUser
    - ErrorGettingAllUsers
    - ErrorCoutingAllUsers
    - ErrorFindingUser
    - ErrorUpdatingUser
    - ErrorCreatingUser
    - ErrorDeletingUser
    - GetAllTechnologies
    - CountAllTechnologies
    - FindTechnology
    - UpdateTechnology
    - CreateTechnology
    - DeleteTechnology
    - ErrorGettingAllTechnologies
    - ErrorCoutingAllTechnologies
    - ErrorFindingTechnology
    - ErrorUpdatingTechnology
    - ErrorCreatingTechnology
    - ErrorDeletingTechnology
  dtos.TechnologyCreateRequestDTO:
    properties:
      name:
        minLength: 2
        type: string
      slug:
        minLength: 2
        type: string
    required:
    - name
    - slug
    type: object
  dtos.TechnologyDTO:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    type: object
  dtos.TechnologyUpdateRequestDTO:
    properties:
      name:
        type: string
      slug:
        type: string
    type: object
  dtos.UserCreateRequestDTO:
    properties:
      full_name:
        minLength: 2
        type: string
      institutional_email:
        type: string
      nickname:
        minLength: 2
        type: string
      personal_email:
        minLength: 5
        type: string
      registration:
        type: string
      slug:
        minLength: 2
        type: string
    required:
    - full_name
    - nickname
    - personal_email
    - slug
    type: object
  dtos.UserDTO:
    properties:
      id:
        type: integer
      nickname:
        type: string
      personal_email:
        type: string
      role:
        $ref: '#/definitions/enums.SystemRoleEnum'
      slug:
        type: string
    type: object
  dtos.UserUpdateRequestDTO:
    properties:
      full_name:
        type: string
      institutional_email:
        type: string
      nickname:
        type: string
      personal_email:
        type: string
      registration:
        type: string
      slug:
        type: string
    type: object
  enums.SystemRoleEnum:
    enum:
    - admin
    - user
    - professor
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleUser
    - RoleProfessor
  icomphub-api_dtos.PaginationDTO-dtos_TechnologyDTO:
    properties:
      items:
        items:
          $ref: '#/definitions/dtos.TechnologyDTO'
        type: array
      page_number:
        example: 1
        type: integer
      page_size:
        example: 10
        type: integer
      total_items:
        example: 20
        type: integer
      total_pages:
        example: 2
        type: integer
    type: object
  icomphub-api_dtos.PaginationDTO-dtos_UserDTO:
    properties:
      items:
        items:
          $ref: '#/definitions/dtos.UserDTO'
        type: array
      page_number:
        example: 1
        type: integer
      page_size:
        example: 10
        type: integer
      total_items:
        example: 20
        type: integer
      total_pages:
        example: 2
        type: integer
    type: object
  icomphub-api_dtos.Response-any:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.Code'
        example: USER_CREATED
      data: {}
      message:
        example: User created successfully
        type: string
      success:
        type: boolean
    type: object
  icomphub-api_dtos.Response-dtos_TechnologyDTO:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.Code'
        example: USER_CREATED
      data:
        $ref: '#/definitions/dtos.TechnologyDTO'
      message:
        example: User created successfully
        type: string
      success:
        type: boolean
    type: object
  icomphub-api_dtos.Response-dtos_UserDTO:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.Code'
        example: USER_CREATED
      data:
        $ref: '#/definitions/dtos.UserDTO'
      message:
        example: User created successfully
        type: string
      success:
        type: boolean
    type: object
  icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_TechnologyDTO:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.Code'
        example: USER_CREATED
      data:
        $ref: '#/definitions/icomphub-api_dtos.PaginationDTO-dtos_TechnologyDTO'
      message:
        example: User created successfully
        type: string
      success:
        type: boolean
    type: object
  icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_UserDTO:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.Code'
        example: USER_CREATED
      data:
        $ref: '#/definitions/icomphub-api_dtos.PaginationDTO-dtos_UserDTO'
      message:
        example: User created successfully
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /technologies:
    get:
      parameters:
      - default: 1
        in: query
        minimum: 1
        name: pageNumber
        required: true
        type: integer
      - default: 10
        in: query
        minimum: 1
        name: pageSize
        required: true
        type: integer
      - example: Nodejs
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_TechnologyDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: List all technologies
      tags:
      - technologies
    post:
      consumes:
      - application/json
      parameters:
      - description: TechnologyCreateRequestDTO
        in: body
        name: TechnologyCreateRequestDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.TechnologyCreateRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Create a technology
      tags:
      - technologies
  /technologies/{id}:
    delete:
      parameters:
      - description: Technology ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Delete a technology
      tags:
      - technologies
    get:
      parameters:
      - description: Technology ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Find a technology
      tags:
      - technologies
    put:
      consumes:
      - application/json
      parameters:
      - description: Technology ID
        in: path
        name: id
        required: true
        type: integer
      - description: TechnologyUpdateRequestDTO
        in: body
        name: TechnologyUpdateRequestDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.TechnologyUpdateRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_TechnologyDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Update a technology
      tags:
      - technologies
  /users:
    get:
      parameters:
      - default: 1
        in: query
        minimum: 1
        name: pageNumber
        required: true
        type: integer
      - default: 10
        in: query
        minimum: 1
        name: pageSize
        required: true
        type: integer
      - example: Ana
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-icomphub-api_dtos_PaginationDTO-dtos_UserDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: List all users
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: UserCreateRequestDTO
        in: body
        name: UserCreateRequestDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.UserCreateRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_UserDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Create an user
      tags:
      - users
  /users/{id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Delete an user
      tags:
      - users
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_UserDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Find an user
      tags:
      - users
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: UserUpdateRequestDTO
        in: body
        name: UserUpdateRequestDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.UserUpdateRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-dtos_UserDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/icomphub-api_dtos.Response-any'
      summary: Update an user
      tags:
      - users
swagger: "2.0"
