[build]
  cmd = "go build -o ./builds/main ./cmd && swag init -g ./cmd/main.go"
  bin = "./builds/main"
  include_ext = ["go"]
  exclude_dir = [
    "builds",
    "docs",
    "tmp"
  ]

[log]
  time = true