services:
  lint:
    container_name: icomphub-api-lint
    image: icomphub-api-lint
    build:
      context: ../../src
      dockerfile: ../docker/ci/lint.Dockerfile # it search the docker file starting by the context folder
    working_dir: /app
    volumes:
      - ../../src/:/app/ # it search the volume starting by the context folder
