info:
  contact: {}
paths:
  /users/:
    get:
      consumes:
      - application/json
      description: Get all users from database
      produces:
      - application/json
      responses: {}
      summary: Get Users
      tags:
      - users
swagger: "2.0"
