name: CI

on:
  push:
    branches: [devel, staging, main]
  pull_request:
    branches: [devel, staging, main]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image for Linter
        run: |
          docker build ./src \
            --file ./docker/ci/linter.Dockerfile \
            --tag icomphub-api-ci-linter:latest

      - name: Run Linter Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/app \
            icomphub-api-ci-linter
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image for Format Check
        run: |
          docker build ./src \
            --file ./docker/ci/format-check.Dockerfile \
            --tag icomphub-api-ci-format-check:latest

      - name: Run Format Check
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/src:/app \
          icomphub-api-ci-format-check
