name: Deploy Devel

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["devel"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: |
          docker build . --file Dockerfile --tag icomphub-api-devel:latest

      - name: Save Docker Image as .tar
        run: |
          docker save icomphub-api-devel:latest -o icomphub-api-devel.tar

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER01_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER01_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker Image to Server
        run: |
          scp icomphub-api-devel.tar ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }}:/tmp/icomphub-api-devel.tar

      - name: Run Docker Image on VPS
        run: |
          ssh ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }} << 'EOF'
            docker load -i /tmp/icomphub-api-devel.tar
            docker stop icomphub-api-devel || true
            docker rm icomphub-api-devel || true
            docker run -d \
              --name icomphub-api-devel \
              -p ${{ vars.API_PORT_DEVEL }}:8000 \
              -e IN_PRODUCTION=true \
              -e INTERNAL_API_PORT=8000 \
              icomphub-api-devel:latest
          EOF
