name: Deploy Staging

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker Image
        run: |
          docker build . --file Dockerfile --tag icomphub-api-staging:latest

      - name: Save Docker Image as .tar
        run: |
          docker save icomphub-api-staging:latest -o icomphub-api-staging.tar

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER01_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER01_HOST }} >> ~/.ssh/known_hosts

      - name: Copy Docker Image to Server
        run: |
          scp icomphub-api-staging.tar ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }}:/tmp/icomphub-api-staging.tar

      - name: Run Docker Image on VPS
        run: |
          ssh ${{ secrets.SERVER01_USER }}@${{ secrets.SERVER01_HOST }} << 'EOF'
            docker load -i /tmp/icomphub-api-staging.tar
            docker stop icomphub-api-staging || true
            docker rm icomphub-api-staging || true
            docker run -d \
              --name icomphub-api-staging \
              -p ${{ vars.API_PORT_STAGING }}:8000 \
              -e IN_PRODUCTION=true \
              -e SWAGGER_API_URL=${{ vars.API_URL_STAGING }} \
              -e INTERNAL_API_PORT=8000 \
              -e DB_HOST=${{ secrets.SERVER01_HOST }} \
              -e DB_PORT=${{ vars.DB_PORT_STAGING }} \
              -e DB_USER=${{ vars.DB_USER_STAGING }} \
              -e DB_PASSWORD=${{ secrets.DB_PW_STAGING }} \
              -e DB_NAME=${{ vars.DB_STAGING }} \
              icomphub-api-staging:latest
          EOF
